### ISSUE TITLE
ERROR ==> Could not find a service builder called laravel-memcached in the builder registry!

### ISSUE THREAD

**Issue by nerdroid23** [lando/laravel#51]
After upgrading to the latest version of lando `v3.21.0-beta.1`, the lando app won't start and I keep getting the error in the title.

I did run `lando setup`
<details><summary>lando setup</summary>

```
lando setup is a convenience command to help you satisify the dependencies needed
to run Lando. Typically it includes the installation and setup of some combination of the below
However, if you already have the needed dependencies it will happily do nothing and exit.

 ◼ Common Lando Plugins
 ◼ Docker Desktop
 ◼ Docker Compose

It will attempt to install plugins first and then it will run any needed setup tasks. For more information on
customizing setup please run lando setup --help

Generating plugin installation matrix... done [nothing to install]

Generating setup task installation matrix... done [nothing to install]

As far as lando setup can tell you are good to go and do not require additional setup!
```
</details>

I tried `lando restart --debug`
<details><summary>lando restart --debug</summary>

```
lando ERROR Error: Could not find a service builder called laravel-memcached in the builder registry!
    at Factory.get (/snapshot/cli/node_modules/@lando/core/lib/factory.js)
    at /snapshot/cli/node_modules/@lando/core/hooks/app-add-v3-services.js
    at arrayEach (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at Function.forEach (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at /snapshot/cli/node_modules/@lando/core/hooks/app-add-v3-services.js
    at AsyncEvents.<anonymous> (/snapshot/cli/node_modules/@lando/core/app.js)
From previous event:
    at AsyncEvents.handle (/snapshot/cli/node_modules/@lando/core/lib/events.js)
    at /snapshot/cli/node_modules/@lando/core/lib/events.js
    at process.processImmediate (node:internal/timers:476:21)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/node_modules/@lando/core/lib/events.js)
    at /snapshot/cli/node_modules/@lando/core/lib/app.js
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (/snapshot/cli/node_modules/@lando/core/tasks/restart.js)
```
</details> 

Is there any other that I can do to make it work or do I just have to downgrade for now...?

**Comment by reynoldsalec** [comment]
@nerdroid23 new Laravel release should fix this issue: https://github.com/lando/laravel/releases/tag/v1.2.0

Run `lando update` and you should be set!

**Comment by nerdroid23** [comment]
@reynoldsalec Thank you!!

I'm having another issue however... running `lando update`. I haven't run in this issue before
<details><summary>lando update --debug</summary>

```Lando would like to update 1 package(s) listed above.
DO YOU CONSENT?: yes
  lando [STARTED] Updating @lando/cli to v3.21.0-beta.2  +4199ms
  lando [FAILED] Lando cannot write to /usr/local/bin!  +0ms
  lando {}  +1ms
  lando ERROR Error: An update error occured! Rerun with lando update --debug for more info.
    at Object.run (/Users/joe/.lando/plugins/@lando/core/tasks/update.js:163:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
From previous event:
    at process.processImmediate (node:internal/timers:476:21)
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at /snapshot/cli/bin/lando.js  +3ms
  lando reporting error action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev +13ms
  lando reported data command=lando update, context=local, devMode=false, instance=11f79071035e658bcf612773a73f264698ff1595, nodeVersion=v18.18.2, mode=cli, type=Darwin, platform=darwin, release=23.3.0, arch=arm64, product=lando, version=3.21.0-beta.3, message=An update error occured! Rerun with lando update --debug for more info., stack=Error: An update error occured! Rerun with lando update --debug for more info.
    at Object.run (update.js:163:23)
    at process.processTicksAndRejections (task_queues:95:5)
From previous event:
    at process.processImmediate (timers:476:21)
From previous event:
    at Object.handler (cli.js)
    at Object.runCommand (command.js:238:44)
    at Object.parseArgs [as _parseArgs] (yargs.js:1063:30)
    at Function.get [as argv] (yargs.js:1004:21)
    at Cli.init (cli.js)
    at Cli.run (cli.js)
    at /snapshot/cli/bin/lando.js, action=error, created=2024-02-21T20:16:02.332Z
```

</details>

**Comment by reynoldsalec** [comment]
@nerdroid23 you've probably seen some of the messages regarding this, but you'll probably want to download the newest version of Lando and try re-running. There were some issues in the `lando update` functionality that we're rolling out fixes for.

**Comment by nerdroid23** [comment]
@reynoldsalec thanks for the heads-up! 🙌🏾
