### ISSUE TITLE
ERROR ==> Could not find a service builder called node in the builder registry!

### ISSUE THREAD

**Issue by UTCGilligan** [lando/laravel#54]
Deleted: wrong project.

**Comment by UTCGilligan** [comment]
```
❯ lando rebuild --debug -y
  lando starting 'lando' version '3.21.0-beta.6' runtime selector... +0ms
  lando merged in additional config source from file '/snapshot/cli/config.yml' +25ms
  lando merged in additional config source from file '/Users/me/.lando/config.yml' +4ms
  lando merged in additional config source from 'LANDO_*' envvars with data {} +1ms
  lando final assembled minconf is {
  lando   configSources: [ '/snapshot/cli/config.yml', '/Users/me/.lando/config.yml' ],
  lando   envPrefix: 'LANDO',
  lando   landoFile: '.lando.yml',
  lando   preLandoFiles: [
  lando     '.lando.base.yml',
  lando     '.lando.dist.yml',
  lando     '.lando.recipe.yml',
  lando     '.lando.upstream.yml'
  lando   ],
  lando   postLandoFiles: [ '.lando.local.yml', '.lando.user.yml' ],
  lando   runtime: 3,
  lando   srcRoot: '/snapshot/cli',
  lando   userConfRoot: '/Users/me/.lando',
  lando   product: 'lando',
  lando   hyperdrive: 'hyperdrive',
  lando   channel: 'stable',
  lando   domain: 'lndo.site',
  lando   mode: 'cli',
  lando   stats: [ { report: true, url: 'https://metrics.lando.dev' } ]
  lando } +0ms
  lando detected an app 'utcwpblogsmultisite' at '/Users/me/Sites/UTC/utcblogsmultisite' +34ms
  lando using '@lando/core' runtime version 3 +0ms
  lando starting lando with 'v3' runtime using cli { ENVPREFIX: undefined, LOGLEVELCONSOLE: 4, USERCONFROOT: undefined, COREBASE: '/Users/me/.lando/plugins/@lando/core' } +28ms
  lando using cli config { commit: false, coreBase: false, dev: false, entrypoint: '/Users/me/.lando/bin/lando', file: '/Users/me/.lando/bin/lando-v3.21.0-beta.6', installPath: '/Users/me/.lando/bin', packaged: true, plugin: '/snapshot/cli', slim: true, source: false } +1ms
  lando using cli config { commit: false, coreBase: false, dev: false, entrypoint: '/Users/me/.lando/bin/lando', file: '/Users/me/.lando/bin/lando-v3.21.0-beta.6', installPath: '/Users/me/.lando/bin', packaged: true, plugin: '/snapshot/cli', slim: true, source: false } +138ms
  lando using cli config { commit: false, coreBase: false, dev: false, entrypoint: '/Users/me/.lando/bin/lando', file: '/Users/me/.lando/bin/lando-v3.21.0-beta.6', installPath: '/Users/me/.lando/bin', packaged: true, plugin: '/snapshot/cli', slim: true, source: false } +10ms
  lando using cli config { commit: false, coreBase: false, dev: false, entrypoint: '/Users/me/.lando/bin/lando', file: '/Users/me/.lando/bin/lando-v3.21.0-beta.6', installPath: '/Users/me/.lando/bin', packaged: true, plugin: '/snapshot/cli', slim: true, source: false } +14ms
  lando starting bootstrap at level app...  +4ms
  lando config bootstrap beginning...  +9ms
  lando emitting event pre-bootstrap-config  +0ms
  lando plugin '@lando/core' loaded from /Users/me/.lando/plugins/@lando/core/index.js  +35ms
  lando plugin '@lando/healthcheck' loaded from /Users/me/.lando/plugins/@lando/core/plugins/healthcheck/index.js  +2ms
  lando plugin '@lando/networking' loaded from /Users/me/.lando/plugins/@lando/core/plugins/networking/index.js  +2ms
  lando plugin '@lando/proxy' loaded from /Users/me/.lando/plugins/@lando/core/plugins/proxy/index.js  +2ms
  lando plugin '@lando/scanner' loaded from /Users/me/.lando/plugins/@lando/core/plugins/scanner/index.js  +2ms
  lando plugin '@lando/sharing' loaded from /Users/me/.lando/plugins/@lando/core/plugins/sharing/index.js  +1ms
  lando plugin '@lando/acquia' loaded from /Users/me/.lando/plugins/@lando/acquia/index.js  +1ms
  lando plugin '@lando/backdrop' loaded from /Users/me/.lando/plugins/@lando/backdrop/index.js  +1ms
  lando plugin '@lando/drupal' loaded from /Users/me/.lando/plugins/@lando/drupal/index.js  +0ms
  lando plugin '@lando/joomla' loaded from /Users/me/.lando/plugins/@lando/joomla/index.js  +1ms
  lando plugin '@lando/lamp' loaded from /Users/me/.lando/plugins/@lando/lamp/index.js  +1ms
  lando plugin '@lando/laravel' loaded from /Users/me/.lando/plugins/@lando/laravel/index.js  +1ms
  lando plugin '@lando/lemp' loaded from /Users/me/.lando/plugins/@lando/lemp/index.js  +1ms
  lando plugin '@lando/memcached' loaded from /Users/me/.lando/plugins/@lando/memcached/index.js  +0ms
  lando plugin '@lando/symfony' loaded from /Users/me/.lando/plugins/@lando/symfony/index.js  +1ms
  lando plugin '@lando/wordpress' loaded from /Users/me/.lando/plugins/@lando/wordpress/index.js  +1ms
  lando removed duplicate plugin entries %o name=@lando/core, path=/Users/me/.lando/plugins/@lando/core, type=local +1ms
  lando emitting event post-bootstrap-config  +1ms
  lando building proxy config...  +1ms
  lando config bootstrap completed.  +1ms
  lando tasks bootstrap beginning...  +0ms
  lando emitting event pre-bootstrap-tasks  +0ms
  lando autoloaded task config  +91ms
  lando autoloaded task destroy  +1ms
  lando autoloaded task info  +0ms
  lando autoloaded task init  +8ms
  lando autoloaded task list  +1ms
  lando autoloaded task logs  +0ms
  lando autoloaded task plugin-add  +1ms
  lando autoloaded task plugin-login  +1ms
  lando autoloaded task plugin-logout  +1ms
  lando autoloaded task plugin-remove  +0ms
  lando autoloaded task poweroff  +1ms
  lando autoloaded task rebuild  +1ms
  lando autoloaded task restart  +1ms
  lando autoloaded task setup  +26ms
  lando autoloaded task share  +1ms
  lando autoloaded task shellenv  +0ms
  lando autoloaded task ssh  +1ms
  lando autoloaded task start  +1ms
  lando autoloaded task stop  +0ms
  lando autoloaded task update  +2ms
  lando autoloaded task version  +0ms
  lando emitting event post-bootstrap-tasks  +3ms
  lando tasks bootstrap completed.  +1ms
  lando engine bootstrap beginning...  +0ms
  lando emitting event pre-bootstrap-engine  +0ms
  lando automoved scripts from /Users/me/.lando/plugins/@lando/core/scripts to /Users/me/.lando/scripts and set to mode 755  +149ms
  lando automoved scripts from /Users/me/.lando/plugins/@lando/core/plugins/proxy/scripts to /Users/me/.lando/scripts and set to mode 755  +4ms
  lando automoved scripts from /Users/me/.lando/plugins/@lando/core/plugins/sharing/scripts to /Users/me/.lando/scripts and set to mode 755  +5ms
  lando automoved scripts from /Users/me/.lando/plugins/@lando/acquia/scripts to /Users/me/.lando/scripts and set to mode 755  +11ms
  lando automoved scripts from /Users/me/.lando/plugins/@lando/backdrop/scripts to /Users/me/.lando/scripts and set to mode 755  +21ms
  lando emitting event post-bootstrap-engine  +1ms
  lando engine bootstrap completed.  +0ms
  lando app bootstrap beginning...  +1ms
  lando emitting event pre-bootstrap-app  +0ms
  lando autodiscovered legacy api 3 builder _appserver  +11ms
  lando autodiscovered legacy api 3 builder _casetup  +0ms
  lando autodiscovered legacy api 3 builder _init  +1ms
  lando autodiscovered legacy api 3 builder _lando  +0ms
  lando autodiscovered legacy api 3 builder _landoutil  +0ms
  lando autodiscovered legacy api 4 builder _service  +0ms
  lando autodiscovered legacy api 3 builder _service  +0ms
  lando autodiscovered legacy api 3 builder _webserver  +0ms
  lando autodiscovered legacy api 4 builder lando  +0ms
  lando autodiscovered legacy api 3 builder lando  +0ms
  lando autodiscovered legacy api 3 builder _proxy  +0ms
  lando autodiscovered legacy api 3 builder _mounter  +0ms
  lando autodiscovered legacy api 3 builder acquia-base  +1ms
  lando autodiscovered legacy api 3 builder acquia-mailhog  +0ms
  lando autodiscovered legacy api 3 builder acquia-mariadb  +0ms
  lando autodiscovered legacy api 3 builder acquia-memcached  +0ms
  lando autodiscovered legacy api 3 builder acquia-mysql  +0ms
  lando autodiscovered legacy api 3 builder acquia-php  +0ms
  lando autodiscovered legacy api 3 builder acquia-postgres  +0ms
  lando autodiscovered legacy api 3 builder acquia  +0ms
  lando autodiscovered legacy api 3 builder backdrop-mariadb  +0ms
  lando autodiscovered legacy api 3 builder backdrop-mssql  +0ms
  lando autodiscovered legacy api 3 builder backdrop-mysql  +0ms
  lando autodiscovered legacy api 3 builder backdrop-nginx  +1ms
  lando autodiscovered legacy api 3 builder backdrop-php  +0ms
  lando autodiscovered legacy api 3 builder backdrop-postgres  +0ms
  lando autodiscovered legacy api 3 builder backdrop  +0ms
  lando autodiscovered legacy api 3 builder _drupaly  +0ms
  lando autodiscovered legacy api 3 builder drupal-mariadb  +0ms
  lando autodiscovered legacy api 3 builder drupal-mssql  +0ms
  lando autodiscovered legacy api 3 builder drupal-mysql  +0ms
  lando autodiscovered legacy api 3 builder drupal-nginx  +0ms
  lando autodiscovered legacy api 3 builder drupal-php  +0ms
  lando autodiscovered legacy api 3 builder drupal-postgres  +0ms
  lando autodiscovered legacy api 3 builder drupal10  +0ms
  lando autodiscovered legacy api 3 builder drupal6  +0ms
  lando autodiscovered legacy api 3 builder drupal7  +1ms
  lando autodiscovered legacy api 3 builder drupal8  +0ms
  lando autodiscovered legacy api 3 builder drupal9  +0ms
  lando autodiscovered legacy api 3 builder joomla-mariadb  +0ms
  lando autodiscovered legacy api 3 builder joomla-mssql  +0ms
  lando autodiscovered legacy api 3 builder joomla-mysql  +0ms
  lando autodiscovered legacy api 3 builder joomla-nginx  +0ms
  lando autodiscovered legacy api 3 builder joomla-php  +0ms
  lando autodiscovered legacy api 3 builder joomla-postgres  +0ms
  lando autodiscovered legacy api 3 builder joomla  +0ms
  lando autodiscovered legacy api 3 builder lamp-mariadb  +0ms
  lando autodiscovered legacy api 3 builder lamp-mongo  +0ms
  lando autodiscovered legacy api 3 builder lamp-mssql  +0ms
  lando autodiscovered legacy api 3 builder lamp-mysql  +1ms
  lando autodiscovered legacy api 3 builder lamp-nginx  +0ms
  lando autodiscovered legacy api 3 builder lamp-php  +0ms
  lando autodiscovered legacy api 3 builder lamp-postgres  +0ms
  lando autodiscovered legacy api 3 builder lamp  +0ms
  lando autodiscovered legacy api 3 builder laravel-mariadb  +0ms
  lando autodiscovered legacy api 3 builder laravel-memcached  +0ms
  lando autodiscovered legacy api 3 builder laravel-mssql  +0ms
  lando autodiscovered legacy api 3 builder laravel-mysql  +0ms
  lando autodiscovered legacy api 3 builder laravel-nginx  +0ms
  lando autodiscovered legacy api 3 builder laravel-php  +0ms
  lando autodiscovered legacy api 3 builder laravel-postgres  +0ms
  lando autodiscovered legacy api 3 builder laravel-redis  +0ms
  lando autodiscovered legacy api 3 builder laravel  +1ms
  lando autodiscovered legacy api 3 builder lemp-mariadb  +0ms
  lando autodiscovered legacy api 3 builder lemp-mongo  +0ms
  lando autodiscovered legacy api 3 builder lemp-mssql  +0ms
  lando autodiscovered legacy api 3 builder lemp-mysql  +0ms
  lando autodiscovered legacy api 3 builder lemp-nginx  +0ms
  lando autodiscovered legacy api 3 builder lemp-php  +0ms
  lando autodiscovered legacy api 3 builder lemp-postgres  +0ms
  lando autodiscovered legacy api 3 builder lemp  +0ms
  lando autodiscovered legacy api 3 builder memcached  +0ms
  lando autodiscovered legacy api 3 builder symfony-mariadb  +0ms
  lando autodiscovered legacy api 3 builder symfony-memcached  +0ms
  lando autodiscovered legacy api 3 builder symfony-mssql  +0ms
  lando autodiscovered legacy api 3 builder symfony-mysql  +0ms
  lando autodiscovered legacy api 3 builder symfony-nginx  +1ms
  lando autodiscovered legacy api 3 builder symfony-php  +0ms
  lando autodiscovered legacy api 3 builder symfony-postgres  +0ms
  lando autodiscovered legacy api 3 builder symfony-redis  +0ms
  lando autodiscovered legacy api 3 builder symfony  +0ms
  lando autodiscovered legacy api 3 builder wordpress-mariadb  +0ms
  lando autodiscovered legacy api 3 builder wordpress-mssql  +0ms
  lando autodiscovered legacy api 3 builder wordpress-mysql  +0ms
  lando autodiscovered legacy api 3 builder wordpress-nginx  +0ms
  lando autodiscovered legacy api 3 builder wordpress-php  +0ms
  lando autodiscovered legacy api 3 builder wordpress-postgres  +1ms
  lando autodiscovered legacy api 3 builder wordpress  +0ms
  lando emitting event post-bootstrap-app  +1ms
  lando app bootstrap completed.  +31ms
  lando bootstrap completed.  +0ms
  lando emitting event post-bootstrap  +0ms
  lando emitting event almost-ready  +1ms
  lando using docker-compose /Applications/Docker.app/Contents/Resources/bin/docker-compose  +1ms
  lando emitting event ready  +7ms
  lando emitting event cli-answers  +2ms
  lando emitting event cli-rebuild-answers  +0ms
  lando loading app utcwpblogsmultisite from config files 0=/Users/me/Sites/UTC/utcblogsmultisite/.lando.yml +83ms
  lando app utcwpblogsmultisite has config name=utcwpblogsmultisite, recipe=wordpress, php=8.2, webroot=web, database=mariadb, xdebug=false, run=[cd $LANDO_MOUNT && composer install, cd $LANDO_MOUNT && cp web/.htaccess.example web/.htaccess, cd $LANDO_MOUNT && cp .env.example .env, cd $LANDO_MOUNT && touch web/app/plugins/.gitkeep && touch web/app/themes/.gitkeep, composer global require laravel/envoy], type=node, ports=[3000:3000], type=mailhog, hogfrom=[appserver], service=appserver, service=theme, service=theme, mailhog=[mailhog.lndo.site] +0ms
  utcwpblogsmultisite initiatilizing app at /Users/me/Sites/UTC/utcblogsmultisite...  +10ms
  lando plugin '@lando/core' loaded from /Users/me/.lando/plugins/@lando/core/app.js  +17ms
  lando plugin '@lando/healthcheck' loaded from /Users/me/.lando/plugins/@lando/core/plugins/healthcheck/app.js  +1ms
  lando plugin '@lando/networking' loaded from /Users/me/.lando/plugins/@lando/core/plugins/networking/app.js  +1ms
  utcwpblogsmultisite proxy settings detected.  +8ms
  lando plugin '@lando/proxy' loaded from /Users/me/.lando/plugins/@lando/core/plugins/proxy/app.js  +4ms
  lando plugin '@lando/scanner' loaded from /Users/me/.lando/plugins/@lando/core/plugins/scanner/app.js  +1ms
  lando plugin '@lando/sharing' loaded from /Users/me/.lando/plugins/@lando/core/plugins/sharing/app.js  +2ms
  lando plugin '@lando/acquia' loaded from /Users/me/.lando/plugins/@lando/acquia/app.js  +1ms
  utcwpblogsmultisite emitting event pre-init  +4ms
  utcwpblogsmultisite building wordpress recipe named  +1ms
  utcwpblogsmultisite building v3 wordpress-php service appserver  +47ms
  lando automoved scripts from /Users/me/.lando/plugins/@lando/wordpress/node_modules/@lando/php/scripts to /Users/me/.lando/scripts and set to mode 755  +101ms
  utcwpblogsmultisite building v3 wordpress-mariadb service database  +79ms
  utcwpblogsmultisite WARN node is not a supported service type.  +21ms
  utcwpblogsmultisite building v3 node service theme  +0ms
  lando ERROR Error: Could not find a service builder called node in the builder registry!
    at Factory.get (/Users/me/.lando/plugins/@lando/core/lib/factory.js:102:25)
    at /Users/me/.lando/plugins/@lando/core/hooks/app-add-v3-services.js:20:35
    at arrayEach (/Users/me/.lando/plugins/@lando/core/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/Users/me/.lando/plugins/@lando/core/node_modules/lodash/lodash.js:9410:14)
    at module.exports (/Users/me/.lando/plugins/@lando/core/hooks/app-add-v3-services.js:12:5)
    at AsyncEvents.<anonymous> (/Users/me/.lando/plugins/@lando/core/app.js:55:85)
    at AsyncEvents.handle (/Users/me/.lando/plugins/@lando/core/lib/events.js:84:25)
From previous event:
    at AsyncEvents.handle (/Users/me/.lando/plugins/@lando/core/lib/events.js:85:22)
    at /Users/me/.lando/plugins/@lando/core/lib/events.js:117:21
    at process.processImmediate (node:internal/timers:476:21)
From previous event:
    at AsyncEvents.emit (/Users/me/.lando/plugins/@lando/core/lib/events.js:111:20)
    at /Users/me/.lando/plugins/@lando/core/lib/app.js:295:66
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  +70ms
  lando reporting error action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev +20ms
  lando reported data command=lando rebuild, context=local, devMode=false, instance=cbf3789a15a0634dd7eb297a276d59b23d2e821f, nodeVersion=v18.18.2, mode=cli, type=Darwin, platform=darwin, release=22.6.0, arch=x64, product=lando, version=3.21.0-beta.6, message=Could not find a service builder called node in the builder registry!, stack=Error: Could not find a service builder called node in the builder registry!
    at Factory.get (factory.js:102:25)
    at /Users/me/.lando/plugins/@lando/core/hooks/app-add-v3-services.js:20:35
    at arrayEach (lodash.js:530:11)
    at Function.forEach (lodash.js:9410:14)
    at module.exports (app-add-v3-services.js:12:5)
    at AsyncEvents.<anonymous> (app.js:55:85)
    at AsyncEvents.handle (events.js:84:25)
From previous event:
    at AsyncEvents.handle (events.js:85:22)
    at /Users/me/.lando/plugins/@lando/core/lib/events.js:117:21
    at process.processImmediate (timers:476:21)
From previous event:
    at AsyncEvents.emit (events.js:111:20)
    at /Users/me/.lando/plugins/@lando/core/lib/app.js:295:66
    at process.processTicksAndRejections (task_queues:95:5), action=error, created=2024-02-29T13:57:56.976Z +0ms
  lando checking docker version compatibility...  +184ms
  lando compatibility results name=compose, link=https://docs.docker.com/desktop/install/mac-install/, satisfied=true, wants=1.x.x || 2.x.x, dockerVersion=true, version=2.24.5, name=desktop, link=https://docs.docker.com/desktop/install/mac-install/, satisfied=true, wants=>=4.0.0 <4.28, dockerVersion=true, version=4.23.0 +0ms
```
